excerpt_separator: ""
pygments: true
markdown: kramdown
title: neves blog
url: "http://blog.nevesbox.com"
author:
  name: "Rafael César Neves"
  email: "rafael.ceesar@gmail.com"
tagline: for web developers
description: "&lt;no&dash;description&#47;&gt;"
paginate: 5
