# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

# source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: Rafael César Neves
description: "A free Jekyll theme for download"
keywords: "Jekyll, theme, free, download, SEO, blog, web"
# tagline: Conteúdo para desenvolvedores
url: http://rafaelcneves.github.io
baseurl: ""

google_analytics: UA-69286309-1
# repo: http://github.com/rafaelcneves/rafaelcneves.github.io
disqus_shortname: "nevesblog"
disqus_site_shortname: "nevesblog"

# Author settings
author:
  name: Rafael César Neves
  job: Full Stack Developer
  bio: "Rails enthusiast, with a lot of ideas, always looking for the best challenges and good coffee."
  thumb: /images/author.jpg
  email: rneves@rocketmail.com
  url: http://rafaelcneves.github.io
  github: http://github.com/rafaelcneves
  twitter: http://twitter.com/rafaelcneves
  facebook: http://facebook.com/rafael.c.neves
  linkedin: http://linkedin.com/in/rafaelcneves
  knowledge:
    - Ruby on Rails
    - MySQL
    - PHP
    - HTML
    - CSS
    - JavaScript
    - jQuery
    - AngularJS
    - PostgreSQL
    - Web Development
    - Ruby
    - Linux
    - HAML
    - SASS
    - CoffeeScript
    - MongoDB
    - Scrum
    - Git
    - Laravel
    - C#
    - Microsoft .NET
    - Microsoft Visual Studio
    - SQLite
    - XML
    - JSON
    - C++
    - UML
    - Java
    - SQL
    - Software Development
    - Desenvolvimento de sites
    - Desenvolvimento de software
    - Banco de dados
    - Sistemas operacionais
    - Segurança da informação
    - Gestão de projetos
    - Gestão de processos
    - Gestão de pessoas
    - Serviços RESTful
    - Aplicativos web
    - Desenvolvimento web
    - Microsoft Project

# navbar pages
navbar:
  - slug: about
    title: About
  # - slug: resume
  #   title: Resume
  # - slug: skills
  #   title: Skills
  - slug: blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
