excerpt_separator: ""
highlighter: rouge
markdown: kramdown
title: Neves Blog
url: "http://rafaelcneves.github.io/"
author:
  name: "Rafael César Neves"
  email: "rafael.ceesar@gmail.com"
tagline: Conteúdo para desenvolvedores
description: "&lt;no&dash;description&#47;&gt;"
paginate: 5
