# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate, jekyll-admin]

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

# source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: Rafael César Neves
description: "Rails enthusiast, with a lot of ideas, always looking for the best challenges and good coffee."
keywords: "Linux, Ruby, Rails, Mysql, Java, web, developer"
tagline: Conteúdo para desenvolvedores
url: http://rafaelcneves.github.io
baseurl:
#baseurl: http://rafaelcneves.github.io

google_analytics: UA-69286309-1
repo: http://github.com/rafaelcneves/rafaelcneves.github.io
disqus_shortname: "nevesblog"
disqus_site_shortname: "nevesblog"

# Author settings
author:
  name: Rafael César Neves
  job: Full Stack Developer
  short_bio: "Rails enthusiast, with a lot of ideas, always looking for the best challenges and good coffee."
  full_bio: "Graduado em Tecnologia em Análise e Desenvolvimento de Sistemas na UDESC, formado pelo SENAI no curso Técnico em Informática, atualmente trabalhando com desenvolvimento web em PHP. Mas possui experiência com desenvolvimento nas linguagens Ruby, C# e de forma breve em desenvolvimento para Android. Atuando em diversas ocasiões com bancos de dados relacionais e não relacionais, principalmente MySQL e PostgreSQL. Já trabalhou com tecnologias de front-end como Angular e Bootstrap. Possuindo também conhecimento em desenvolvimento mobile para Android."
  thumb: /images/author.jpg
  email: rneves@rocketmail.com
  url: http://rafaelcneves.github.io
  github: http://github.com/rafaelcneves
  twitter: http://twitter.com/rafaelcneves
  facebook: http://facebook.com/rafael.c.neves
  linkedin: http://linkedin.com/in/rafaelcneves
  stackoverflow: http://stackoverflow.com/users/2116875/rneves
  skills:
    - Ruby on Rails
    - MySQL
    - PHP
    - HTML
    - CSS
    - JavaScript
    - jQuery
    - AngularJS
    - PostgreSQL
    - Web Development
    - Ruby
    - Linux
    - HAML
    - SASS
    - CoffeeScript
    - MongoDB
    - Scrum
    - Git
    - Laravel
    - C#
    - Microsoft .NET
    - Microsoft Visual Studio
    - SQLite
    - XML
    - JSON
    - C++
    - UML
    - Java
    - SQL

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
