# Build settings
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge
# plugins: [jekyll-paginate]
# , jekyll-admin

# paginate: 12
# paginate_path: "/page/:num/"
comments: true

# source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: Rafael César Neves
description: "Rails enthusiast, with a lot of ideas, always looking for the best challenges and good coffee."
keywords: "Linux, Ruby, Rails, Mysql, Java, web, developer"
tagline: Conteúdo para desenvolvedores
url: https://rafaelcneves.github.io

repo: https://github.com/rafaelcneves/rafaelcneves.github.io
disqus_shortname: "nevesblog"
disqus_site_shortname: "nevesblog"

exclude:
  - gulp
  - node_modules
  - bower
  - bower_components
  - config.rb
  - src
  - Gemfile
  - Gemfile.lock
  - .rvmrc
  - .rbenv-version
  - package.json
  - gulpfile.js
  - README.md
  - Rakefile
  - changelog.md
  - vendor
  - Makefile
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - LICENSE
  - PULL_REQUEST_TEMPLATE.md
